### ISSUE TITLE
Indexing always fails with Xcode 10.2 beta

### ISSUE THREAD

**Issue by alex-vasenin** [peripheryapp/periphery#8]
Hello,

If I point `xcode-select` to Xcode 10.2 beta 2, `periphery scan` indexing phase fails with error:

> error: SourceKit editorOpen request failed for file '/Users/myUser/longPath/MyClass.swift': Retrieving both the document structure and a syntax tree at the same time is not supported. Use the syntax tree to compute the document structure.

You can find the message in [SwiftEditor sources](https://github.com/apple/swift/blob/master/tools/SourceKit/lib/SwiftLang/SwiftEditor.cpp).

Please fix.

**Comment by ileitch** [comment]
This is now fixed in the `xcode10.2` branch.

**Comment by Sam-Spencer** [comment]
Still having this issue on the public release of Xcode 10.2

**Comment by salutis** [comment]
+1 with @Sam-Spencer 

I've just compiled the `xcode10.2` branch, and Periphery failed with the following error:

```
* Inspecting project configuration...
* Building Acrostics...
* Indexing...
objc[30286]: __SwiftNativeNSError object 0x7f85eb111ab0 overreleased while already deallocating; break on objc_overrelease_during_dealloc_error to debug
error: SourceKit editorOpen request failed for file '[REDACTED]': Retrieving both the document structure and a syntax tree at the same time is not supported. Use the syntax tree to compute the document structure.
```

This is still broken.

**Comment by salutis** [comment]
Oh, this is a closed issue. Opened #28.

**Comment by linkrjr** [comment]
Has this actually been fixed? if it has, in what version?
I am still running into this problem.
I am running periphery version 1.4.0 from homebrew integrated into xcode 10.2

**Comment by premuvt** [comment]
I am getting this issue on periphery scan.

* Executing command:
periphery scan \
  --workspace "/Users/jayanthibaskar/CL-Wellness-Vital-signs-iOS/CLWellnessAndVitalSign/Connectedlife MxHi.xcworkspace/" \
  --schemes "Citta.ai","CittaNotificationPresentationExtension ","CittaToday.ai" \
  --targets "Citta" \
  --retain-public

* Inspecting project configuration...
* Building CittaNotificationPresentationExtension ...
* Building CittaToday.ai...
* Building Citta.ai...
* Indexing...
**error: SourceKit editorOpen request failed for file '/Users/jayanthibaskar/CL-Wellness-Vital-signs-iOS/CLWellnessAndVitalSign/PersonalCare/SettingsPage/UnitsTableViewController.swift': Retrieving both the document structure and a syntax tree at the same time is not supported. Use the syntax tree to compute the document structure.**

**Comment by plezervi** [comment]
Experiencing the same with a fresh install with brew cask

**Comment by ileitch** [comment]
This is fixed in `master`, but I need to make a couple more fixes before the next release. I'm aiming to do so this weekend.

**Comment by plezervi** [comment]
Awesome, thank you @ileitch ! I can confirm, everything is working like charm after building from master

**Comment by MrPovilas** [comment]
@ileitch Hi! Any updates?
