### ISSUE TITLE
Periphery does not see unused code in Xcode 16’s new synchronized folder format

### ISSUE THREAD

**Issue by neilsardesai** [peripheryapp/periphery#828]
Periphery works as expected when using groups in Xcode. However, when [groups are converted to folders](https://developer.apple.com/documentation/xcode/managing-files-and-folders-in-your-xcode-project#Convert-groups-to-folders), it seems like Periphery no longer sees code within those folders.

I’ve attached a screen recording and a sample project demonstrating this issue:

https://github.com/user-attachments/assets/535237dc-d32c-4f5a-8490-828dcc0dfd98

[Sample.zip](https://github.com/user-attachments/files/17511229/Sample.zip)

**Comment by F1248** [comment]
Same issue here with Periphery version 2.21.1.

**Comment by neilsardesai** [comment]
Seems like the issue still exists in 2.21.2

**Comment by Foixa** [comment]
any update?

**Comment by michalnowak061** [comment]
same here

**Comment by ileitch** [comment]
Hey all, yes I look into this soon. It may already "Just Work" with the 3.0 beta, but I've not tried yet.

**Comment by F1248** [comment]
> It may already "Just Work" with the 3.0 beta, but I've not tried yet.

I can confirm that this is fixed in Periphery 3.0.0 beta 5 and 6, thank you!

**Comment by ileitch** [comment]
This issue should now be resolved in 3.0.0. Let me know if you continue to experience this issue and I will reinvestigate.

**Comment by dusi** [comment]
@ileitch we're still experiencing this issue even with `3.0.1` for the following folder structure (our project uses a root-level "Folder" where we store all SPMs).

```
FolderA
  Foo.swift
Sample
  Sample
    ContentView.swift
    ...
  Sample.xcodeproj
Sample.xcworkspace
```

Attaching a project that demonstrates the above setup: 
[Sample.zip](https://github.com/user-attachments/files/18308525/Sample.zip)

Running `periphery` from the root of the project
```
periphery scan --setup --verbose
```

Results into the following error
```
[version] 3.0.1
[shell] swift -version
Apple Swift version 6.0.3 (swiftlang-6.0.3.1.10 clang-1600.0.30.1)
Target: arm64-apple-macosx15.0
Welcome to Periphery!
This guided setup will help you select the appropriate configuration for your project.

* Detected Xcode project
* Inspecting project...
[shell] xcodebuild -version
Xcode 16.2
Build version 16C5032a
[xcode:workspace] Loading /Users/dusi/Documents/Sample/Sample.xcworkspace
error: (Error) unknownName("FileSystemSynchronizedGroup")
```

**Comment by ileitch** [comment]
@dusi Can you please open a bub report at https://github.com/tuist/XcodeProj with your sample project? The problem is that your `FileSystemSynchronizedGroup` is an attribute on the workspace, rather than the project, which it appears is not supported by https://github.com/tuist/XcodeProj. As a workaround, you can move the folder reference to the project instead.
